### ISSUE TITLE
Can we replace the spinner with another gif? Will doing so break it? (Linux-510-Manjaro)

### ISSUE THREAD

**Issue by dakshcs** [Blacksuan19/Bootsplash-Themes#4]
This is meant for bootsplash-theme-amd
Also same question for the AMD Logo.
And if it even is possible to replace these.

**Comment by Blacksuan19** [comment]
Replacing the logo should work fine, not sure about the spinner tho you could try

**Comment by dakshcs** [comment]
@Blacksuan19 How do i modify this from the package? The one i cloned from git gives a permission denied error when installing, so i just installed from pamac. any ideas how i could modify that?

**Comment by Blacksuan19** [comment]
Read the PKGBUILD, where's everything installed is specified there  

_Sent from my BASIC using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by dakshcs** [comment]
ummm, where is the pkgbuild? and what pkgbuild are you talking about? the one made from the script or the one used by pamac?.


_i am certified dumb please dont be toxic to me this happens a lot of times._

**Comment by Blacksuan19** [comment]
This is it 
https://github.com/Blacksuan19/Bootsplash-Themes/blob/master/manjaro-bootsplash-amd/PKGBUILD
